name: Publish Extension on Firefox's and Chrome's extension marketplaces

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release-firefox:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Enable Corepack
        run: corepack enable pnpm

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Zip
        run: pnpm zip:firefox

      - name: Get extension data
        id: extension
        run: |
          ID=$(jq -r '.browser_specific_settings.gecko.id' .output/firefox-mv2/manifest.json)
          VERSION=$(jq -r '.version' .output/firefox-mv2/manifest.json)
          
          echo "VERSION: $VERSION"
          echo "ID: $ID"

          echo "id=$ID" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Release to Firefox
        uses: session567/release-firefox-addon@temp
        with:
          addon-id: ${{ steps.extension.outputs.id }}
          addon-path: .output/hte-${{ steps.extension.outputs.version }}-firefox.zip
          source-path: .output/hte-${{ steps.extension.outputs.version }}-sources.zip
          release-note: "${{ github.event.release.body }}"
          license: GPL-3.0-only
          auth-api-issuer: ${{ secrets.FIREFOX_API_KEY }}
          auth-api-secret: ${{ secrets.FIREFOX_API_SECRET }}

  release-chrome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Enable Corepack
        run: corepack enable pnpm

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Zip
        run: pnpm zip

      - name: Release to Chrome
        uses: browser-actions/release-chrome-extension@latest
        with:
          extension-id: bbpinjphilaocfmgllmgihlbmnooeglo
          extension-path: extension.zip
          oauth-client-id: ${{ secrets.CHROME_CLIENT_ID }}
          oauth-client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          oauth-refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
